### ISSUE TITLE
old versions not published to npm

### ISSUE THREAD

**Issue by seiyria** [gazmull/discord-paginationembed#27]
I'm trying to use 0.8.0 (as it seems discord 12 isn't yet on npm) and I checked npm. It seems 0.8.0 is not published there - can you do that?

**Comment by gazmull** [comment]
Hi. The NPM publishes started from [1.0.0-beta.0](https://github.com/gazmull/discord-paginationembed/blob/master/CHANGELOG.md#100-beta0---2019-03-25). There is no plan to publish the previous versions (0.x), because they were not configured for NPM publish.

If you're requesting this for the sake of using this with DJS v11 (#28), I'm afraid that v11 is only supported until [0.7.7-v11](https://github.com/gazmull/discord-paginationembed/tree/0.7.7-v11). You can install v11 with `npm i gazmull/discord-paginationembed#v11` (heads up: the docs site isn't compatible with the last v11 branch's version, refer to [API Changes](https://github.com/gazmull/discord-paginationembed/blob/master/UPDATING_V1.md#showpageindicator--setpageindicator) for differences).

**Comment by seiyria** [comment]
I see, thanks.
