### ISSUE TITLE
Reaction navigation buttons in DM's doesn't go to initial state

### ISSUE THREAD

**Issue by propaneko** [gazmull/discord-paginationembed#30]
Hi, great plugin it helped me a lot building my small Discord Bot. But I have small problem with reaction buttons. In guilds they works very well, after clicking reaction it goes back to initial state. But in DM's after clicking emoji reaction it stays in the same state and user needs to "unclick" it before continuing. Is there any possible fix for it?

**Comment by gazmull** [comment]
Hello,

Thanks for using this utility! Unfortunately it isn't possible to mirror the behaviour on guilds to DMs, because Discord prohibits removing user's reactions aside from the client's. I could suggest deleting the message and then calling `.build()` to the instance again, but it's not really ideal since it will get your client ratelimited quick and/or the utility may not be suited well for that situation (unless it is a functionEmoji and [you've stopped the instance from awaiting any react](https://github.com/gazmull/discord-paginationembed/blob/master/CHANGELOG.md#added) and then call `.build()` again).

**Comment by propaneko** [comment]
Thanks a lot for the fast response! 

That's a shame we can get the same behaviour in both places, but it's understandable. Anyway thanks for the tips, will try to figure something out from it!

**Comment by gazmull** [comment]
You're welcome. I feel the same way since I use this for DMs as well, but can't help it. 😐
