### ISSUE TITLE
Get message object?

### ISSUE THREAD

**Issue by foxt** [gazmull/discord-paginationembed#42]
Is it possible to get the message object used by an Embeds pagination or attach a pagination to a pre-existing message?

**Comment by gazmull** [comment]
It is via [`<PaginationEmbed>.clientAssets`](https://docs.thegzm.space/discord-paginationembed/stable/interfaces/clientassets.html). If you passed a message object (client's own message) to `clientAssets` via [`setClientAssets`](https://docs.thegzm.space/discord-paginationembed/stable/classes/paginationembed.html#setclientassets) method it will edit that message instead of sending a new one.

**Comment by foxt** [comment]
Oh, thanks! ~~Do I have to do anything special to do that? Simply passing the msg object to the setClientAssets isn't working for me, it just sends a new message rather than editing the previous message. The document doesn't make it clear to me what a clientAsset is.~~
```js
/**
 * @param {DiscordJS.Message} m     User's message that invoked this paginator
 * @param {DiscordJS.Message} msg Bot's message that's sent as a reply to the user.
**/
new EmbedsMode()
    .setArray(embeds)
    .setAuthorizedUsers([m.author.id])
    .setChannel(m.channel)
    .setClientAssets(msg)
    .setPageIndicator(true)
    .build();
```

**EDIT:** It needs to be an object with the message param set, like so `.setClientAssets({message:await msg})`

**Comment by gazmull** [comment]
Please carefully read the documentation linked above, you need to pass the message object as a property. `clientAssets` is an object that has two properties: `message` and `prompt`.
```js
new EmbedsMode()
    .setArray(embeds)
    .setAuthorizedUsers([m.author.id])
    .setChannel(m.channel)
    .setClientAssets({ message: msg }) // message property
    .setPageIndicator(true)
    .build();
```
